### ISSUE TITLE
UserAgentUtils 包名不对

### ISSUE THREAD

**Issue by xhy008** [ThorQin/thor-toolkit#1]
文件：
thor-toolkit-web/src/main/java/com/github/thorqin/toolkit/web/utility/UserAgentUtils.java
包定义：
package com.github.thorqin.toolkit.utility;

目前我是把此类移回到以下目录：
thor-toolkit-core/src/main/java/com/github/thorqin/toolkit/utility

**Comment by ThorQin** [comment]
感谢，指正。:-)

**Comment by ThorQin** [comment]
已修复。
