### ISSUE TITLE
关于ClientSession

### ISSUE THREAD

**Issue by xhy008** [ThorQin/thor-toolkit#2]
目前框架默认使用ClientSession，而使用Cookie方式来存储session数据，容易受到cookie容量的限制，而产生如下异常：

java.io.IOException: Response header too large

对于此类异常是否有什么好的建议？（除替换为ServerSession）

**Comment by ThorQin** [comment]
虽然客户端session有容量限制，不过好处是免去了群集服务器session同步，所以我还是比较倾向于使用客户端session，一般session中我只是存放用户的登录信息，4k的容量肯定够用了，存放太多的内容也会造成传输的浪费，毕竟每次请求都会携带session，不知道业务上是不是真的有需要存放大量的数据，对于不是每次请求都需要处理的非热数据放在数据库中也就够用了，使用频率稍高的数据可以放到缓存中使用，如果真的存在非要放到session中的大体积数据的话，只好放弃客户端session了，建议使用一些缓存服务包装成session存储，比如redis之类的，只要实现websession接口就可以集成到框架中使用，你有什么想法咱么可以讨论一下。

**Comment by ThorQin** [comment]
另外有一些数据如果场景适用的话也可以存储到客户端sessionStore中。这样有些数据直接在客户端显示不用请求服务器了。

**Comment by xhy008** [comment]
了解，谢谢回复。
