### ISSUE TITLE
Serializer.loadTextFile方法，建议显式关闭文件流

### ISSUE THREAD

**Issue by xhy008** [ThorQin/thor-toolkit#3]
/thor-toolkit-core/src/main/java/com/github/thorqin/toolkit/utility/Serializer.java

![2015-09-29_150718](https://cloud.githubusercontent.com/assets/716954/10157380/366b172e-66bc-11e5-80a4-4ced065d513d.jpg)

目前遇到的问题，使用<tt:script src="*.js">时，当打开页面后，引用的js就不能编辑、保存了，提示其它程序占用。我想可能是因为这个文件流没有显式关闭的原因。（隐式关闭，我没有查到jvm是在什么时机处理的）

**Comment by ThorQin** [comment]
你列出的这个方法已经关闭了文件流，这里使用了java7中的auto close 特性。你碰到的问题是不是在jetty中调试的时候不能编辑静态页面和js呢？jetty自己有个问题，运行时如果不做特殊设定，它会锁定静态资源，可能是为了提高效率。你可以搜索jetty锁定页面之类的就能找到解决办法，框架生成的例子程序中在资源目录中有一个xml就是解决这个问题的，如果没删掉它应该是可以编辑的，不知道你那里的环境有什么不同。

**Comment by xhy008** [comment]
谢谢解答，我使用的是jetty。
