### ISSUE TITLE
com/github/thorqin/toolkit/validation/Validator.java的多语言

### ISSUE THREAD

**Issue by xhy008** [ThorQin/thor-toolkit#4]
目前使用了com.github.thorqin.toolkit.validation.annotation.*校验方式，但在框架校验时返回的都是英文的错误消息，请问是否有什么好的办法可以解决此处的多语言问题？（或者是显示成中文）

**Comment by ThorQin** [comment]
提醒用户输入错误的校验我本来是希望由前端来实现的，服务器的校验只是确保前端不会绕过前台校验而发送异常的数据，所以服务器端的校验没有发送用户友好的错误消息。由于前台校验实现起来也很简单（如果使用 tui 组件的话，只要设置 data-validator 属性就可以了），不需发送请求，而且交互性更好（比如还可以设置焦点、多个字段一起校验等），所以我建议如果可能最好还是由前台来校验。
不过我在明后天会再提交一次代码，以便支持让 validator 直接返回用户友好的多语言的错误消息。比如：
````java
class User {
  @ValidateString(name="姓名")
  public String name;
  @ValidateNumber(min = 40, name="message.user.age")
  public int age;
  @ValidateString
  public String phone;
}
//......

@WebEntry(method = POST)
public void SomeMethod(@Entity @Validate User user) {
  //......
}
````
以上代码如果某个字段校验失败会返回下面的消息：
Verify failed: 'age':  value should equal or great than 40
如果在 message.zh_CN.properties 中添加了中文翻译，则可以显示你希望的描述，如：
校验失败：'年龄':  应该大于等于 40

新的代码版本是 1.2，这个版本中做了几处修改，主要有：
* 添加内置的定时任务服务，支持注解和配置文件
* 添加对redis服务的支持
* 加强了 dbservice 服务的功能，添加了嵌套事物，查询支持 in 参数等...
* DBRouter 支持java 层面的 validation
* 日志文件名称使用日期命名，按天分割
* 应用程序分组，同组应用共享数据目录和配置文件，而拥有不同的日志文件
* 使得 logger, configManager, application 都成为内置服务，方便引用
* Validator 返回友好提示
* 其他 bug 修复和改进等...

建议下载新版本的代码并升级对 thor-toolkit 的版本引用到 1.2，现有应用程序可能需要做出一点点修改，以适应一些命名的变更，但是改动不会太大。
:smile:

**Comment by xhy008** [comment]
好的，谢谢。

**Comment by ThorQin** [comment]
已经更新了哦。
